package com.zking.gofcrm.basd.mapper;

import com.zking.gofcrm.basd.model.Dictionary;
import com.zking.gofcrm.common.util.combo.Combo;

import java.util.List;
import java.util.Map;

public interface DictionaryMapper {


    /**
     * 插入新的字典数据
     * @param record
     * @return
     */
    int insert(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_dict
     *
     * @mbg.generated
     */
    Dictionary selectByPrimaryKey(Integer dictId);

    /**
     * 修改字典表的数据
     * @param record
     * @return
     */
    int updateByPrimaryKeySelective(Dictionary record);

    /**
     * 查询一个集合
     * @param map
     * @return
     */
    List<Dictionary> selectByMap(Map<String, String[]> map);


    /**
     * 获取数据字典类型集合
     * @return
     */
    List<Combo> getDictTypes();

    int deletePrimaryKey(Integer dictId);

}