package com.zking.gofcrm.basd.mapper;

import com.zking.gofcrm.basd.model.SellProduct;

public interface SellProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String prodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_product
     *
     * @mbg.generated
     */
    int insert(SellProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_product
     *
     * @mbg.generated
     */
    int insertSelective(SellProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_product
     *
     * @mbg.generated
     */
    SellProduct selectByPrimaryKey(String prodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SellProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SellProduct record);
}