package com.zking.gofcrm.basd.mapper;

import com.zking.gofcrm.basd.model.SellStorage;

public interface SellStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer stkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_storage
     *
     * @mbg.generated
     */
    int insert(SellStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_storage
     *
     * @mbg.generated
     */
    int insertSelective(SellStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_storage
     *
     * @mbg.generated
     */
    SellStorage selectByPrimaryKey(Integer stkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SellStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sell_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SellStorage record);
}