package com.zking.gofcrm.authority.model;

import org.springframework.stereotype.Component;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table crm_id_suf
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Component
public class CrmIdSufUtil implements Serializable {
    /**
     * Database Column Remarks:
     *   主键编号规则表 编号， 自动增长
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_id_suf.cis_id
     *
     * @mbg.generated
     */
    private Integer cisId;

    /**
     * Database Column Remarks:
     *   所属表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_id_suf.cis_table
     *
     * @mbg.generated
     */
    private String cisTable;

    /**
     * Database Column Remarks:
     *   时间 yyyy-MM-dd
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_id_suf.cis_date
     *
     * @mbg.generated
     */
    private Date cisDate;

    /**
     * Database Column Remarks:
     *   标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_id_suf.cis_key
     *
     * @mbg.generated
     */
    private Integer cisKey = 100001;

    public CrmIdSufUtil(){}

    public CrmIdSufUtil(String cisTable, Date cisDate, Integer cisKey) {
        this.cisTable = cisTable;
        this.cisDate = cisDate;
        this.cisKey = cisKey;
    }

    public CrmIdSufUtil(String cisTable, Date cisDate) {
        this.cisTable = cisTable;
        this.cisDate = cisDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_id_suf.cis_id
     *
     * @return the value of crm_id_suf.cis_id
     *
     * @mbg.generated
     */
    public Integer getCisId() {
        return cisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_id_suf.cis_id
     *
     * @param cisId the value for crm_id_suf.cis_id
     *
     * @mbg.generated
     */
    public void setCisId(Integer cisId) {
        this.cisId = cisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_id_suf.cis_table
     *
     * @return the value of crm_id_suf.cis_table
     *
     * @mbg.generated
     */
    public String getCisTable() {
        return cisTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_id_suf.cis_table
     *
     * @param cisTable the value for crm_id_suf.cis_table
     *
     * @mbg.generated
     */
    public void setCisTable(String cisTable) {
        this.cisTable = cisTable == null ? null : cisTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_id_suf.cis_date
     *
     * @return the value of crm_id_suf.cis_date
     *
     * @mbg.generated
     */
    public Date getCisDate() {
        return cisDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_id_suf.cis_date
     *
     * @param cisDate the value for crm_id_suf.cis_date
     *
     * @mbg.generated
     */
    public void setCisDate(Date cisDate) {
        this.cisDate = cisDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_id_suf.cis_key
     *
     * @return the value of crm_id_suf.cis_key
     *
     * @mbg.generated
     */
    public Integer getCisKey() {
        return cisKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_id_suf.cis_key
     *
     * @param cisKey the value for crm_id_suf.cis_key
     *
     * @mbg.generated
     */
    public void setCisKey(Integer cisKey) {
        this.cisKey = cisKey;
    }
}