package com.zking.gofcrm.authority.model;

import org.apache.ibatis.type.Alias;
import org.springframework.stereotype.Component;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_authority
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Component
public class SysAuthority implements Serializable {
    /**
     * Database Column Remarks:
     *   权限编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.auth_id
     *
     * @mbg.generated
     */
    private String authId;

    /**
     * Database Column Remarks:
     *   父权限编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.auth_parent_id
     *
     * @mbg.generated
     */
    private String authParentId;

    /**
     * Database Column Remarks:
     *   权限类型 包括 Folder Document
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.auth_type
     *
     * @mbg.generated
     */
    private String authType;

    /**
     * Database Column Remarks:
     *   权限名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.auth_text
     *
     * @mbg.generated
     */
    private String authText;

    /**
     * Database Column Remarks:
     *   权限的URL
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.auth_url
     *
     * @mbg.generated
     */
    private String authUrl;

    /**
     * Database Column Remarks:
     *   权限描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.auth_tip
     *
     * @mbg.generated
     */
    private String authTip;

    /**
     * 权限对应的角色
     */
    private String authLv;

    /**
     * 权限的图标
     */
    private String authImage;


    public String getAuthImage() {
        return authImage;
    }

    public void setAuthImage(String authImage) {
        this.authImage = authImage;
    }

    public String getAuthLv() {
        return authLv;
    }

    public void setAuthLv(String authLv) {
        this.authLv = authLv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.auth_id
     *
     * @return the value of sys_authority.auth_id
     *
     * @mbg.generated
     */
    public String getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.auth_id
     *
     * @param authId the value for sys_authority.auth_id
     *
     * @mbg.generated
     */
    public void setAuthId(String authId) {
        this.authId = authId == null ? null : authId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.auth_parent_id
     *
     * @return the value of sys_authority.auth_parent_id
     *
     * @mbg.generated
     */
    public String getAuthParentId() {
        return authParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.auth_parent_id
     *
     * @param authParentId the value for sys_authority.auth_parent_id
     *
     * @mbg.generated
     */
    public void setAuthParentId(String authParentId) {
        this.authParentId = authParentId == null ? null : authParentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.auth_type
     *
     * @return the value of sys_authority.auth_type
     *
     * @mbg.generated
     */
    public String getAuthType() {
        return authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.auth_type
     *
     * @param authType the value for sys_authority.auth_type
     *
     * @mbg.generated
     */
    public void setAuthType(String authType) {
        this.authType = authType == null ? null : authType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.auth_text
     *
     * @return the value of sys_authority.auth_text
     *
     * @mbg.generated
     */
    public String getAuthText() {
        return authText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.auth_text
     *
     * @param authText the value for sys_authority.auth_text
     *
     * @mbg.generated
     */
    public void setAuthText(String authText) {
        this.authText = authText == null ? null : authText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.auth_url
     *
     * @return the value of sys_authority.auth_url
     *
     * @mbg.generated
     */
    public String getAuthUrl() {
        return authUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.auth_url
     *
     * @param authUrl the value for sys_authority.auth_url
     *
     * @mbg.generated
     */
    public void setAuthUrl(String authUrl) {
        this.authUrl = authUrl == null ? null : authUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.auth_tip
     *
     * @return the value of sys_authority.auth_tip
     *
     * @mbg.generated
     */
    public String getAuthTip() {
        return authTip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.auth_tip
     *
     * @param authTip the value for sys_authority.auth_tip
     *
     * @mbg.generated
     */
    public void setAuthTip(String authTip) {
        this.authTip = authTip == null ? null : authTip.trim();
    }
}