package com.zking.gofcrm.authority.model;

import org.apache.ibatis.type.Alias;
import org.springframework.stereotype.Component;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_function
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Component
public class SysFunction implements Serializable {
    /**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.fun_id
     *
     * @mbg.generated
     */
    private String funId;

    /**
     * Database Column Remarks:
     *   功能名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.fun_name
     *
     * @mbg.generated
     */
    private String funName;

    /**
     * Database Column Remarks:
     *   实现功能的请求URL
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.fun_path
     *
     * @mbg.generated
     */
    private String funPath;

    /**
     * Database Column Remarks:
     *   实现功能的请求参数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.fun_parameter
     *
     * @mbg.generated
     */
    private String funParameter;

    /**
     * Database Column Remarks:
     *   实现功能的方法
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.fun_method
     *
     * @mbg.generated
     */
    private String funMethod;

    /**
     * Database Column Remarks:
     *   功能说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function.fun_desc
     *
     * @mbg.generated
     */
    private String funDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.fun_id
     *
     * @return the value of sys_function.fun_id
     *
     * @mbg.generated
     */
    public String getFunId() {
        return funId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.fun_id
     *
     * @param funId the value for sys_function.fun_id
     *
     * @mbg.generated
     */
    public void setFunId(String funId) {
        this.funId = funId == null ? null : funId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.fun_name
     *
     * @return the value of sys_function.fun_name
     *
     * @mbg.generated
     */
    public String getFunName() {
        return funName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.fun_name
     *
     * @param funName the value for sys_function.fun_name
     *
     * @mbg.generated
     */
    public void setFunName(String funName) {
        this.funName = funName == null ? null : funName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.fun_path
     *
     * @return the value of sys_function.fun_path
     *
     * @mbg.generated
     */
    public String getFunPath() {
        return funPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.fun_path
     *
     * @param funPath the value for sys_function.fun_path
     *
     * @mbg.generated
     */
    public void setFunPath(String funPath) {
        this.funPath = funPath == null ? null : funPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.fun_parameter
     *
     * @return the value of sys_function.fun_parameter
     *
     * @mbg.generated
     */
    public String getFunParameter() {
        return funParameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.fun_parameter
     *
     * @param funParameter the value for sys_function.fun_parameter
     *
     * @mbg.generated
     */
    public void setFunParameter(String funParameter) {
        this.funParameter = funParameter == null ? null : funParameter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.fun_method
     *
     * @return the value of sys_function.fun_method
     *
     * @mbg.generated
     */
    public String getFunMethod() {
        return funMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.fun_method
     *
     * @param funMethod the value for sys_function.fun_method
     *
     * @mbg.generated
     */
    public void setFunMethod(String funMethod) {
        this.funMethod = funMethod == null ? null : funMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function.fun_desc
     *
     * @return the value of sys_function.fun_desc
     *
     * @mbg.generated
     */
    public String getFunDesc() {
        return funDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function.fun_desc
     *
     * @param funDesc the value for sys_function.fun_desc
     *
     * @mbg.generated
     */
    public void setFunDesc(String funDesc) {
        this.funDesc = funDesc == null ? null : funDesc.trim();
    }
}