package com.zking.gofcrm.authority.model;

import org.apache.ibatis.type.Alias;
import org.springframework.stereotype.Component;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_role
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Component
public class SysRole implements Serializable {
    /**
     * Database Column Remarks:
     *   角色编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_id
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     * Database Column Remarks:
     *   角色名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_name
     *
     * @mbg.generated
     */
    private String roleName;

    /**
     * Database Column Remarks:
     *   角色描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_desc
     *
     * @mbg.generated
     */
    private String roleDesc;

    /**
     * Database Column Remarks:
     *   角色状态 0可用 1不可用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_flag
     *
     * @mbg.generated
     */
    private Integer roleFlag;


    /**
     * 角色别名
     */
    private String roleAlias;

    /**
     * 角色的权限
     */
    private List<SysAuthority> authzList = new ArrayList<SysAuthority>();

    /**
     * 角色的功能
     */
    private List<SysFunction> functionList = new ArrayList<SysFunction>();


    public String getRoleAlias() {
        return roleAlias;
    }

    public void setRoleAlias(String roleAlias) {
        this.roleAlias = roleAlias;
    }

    public List<SysAuthority> getAuthzList() {
        return authzList;
    }

    public void setAuthzList(List<SysAuthority> authzList) {
        this.authzList = authzList;
    }

    public List<SysFunction> getFunctionList() {
        return functionList;
    }

    public void setFunctionList(List<SysFunction> functionList) {
        this.functionList = functionList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_id
     *
     * @return the value of sys_role.role_id
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_id
     *
     * @param roleId the value for sys_role.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_name
     *
     * @return the value of sys_role.role_name
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_name
     *
     * @param roleName the value for sys_role.role_name
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_desc
     *
     * @return the value of sys_role.role_desc
     *
     * @mbg.generated
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_desc
     *
     * @param roleDesc the value for sys_role.role_desc
     *
     * @mbg.generated
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_flag
     *
     * @return the value of sys_role.role_flag
     *
     * @mbg.generated
     */
    public String getRoleFlag() {
        switch (roleFlag){
            case 0:
                return "可用";
            case 1:
                return "不可用";
            default:
                return roleFlag.toString();
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_flag
     *
     * @param roleFlag the value for sys_role.role_flag
     *
     * @mbg.generated
     */
    public void setRoleFlag(Integer roleFlag) {
        this.roleFlag = roleFlag;
    }
}