package com.zking.gofcrm.authority.mapper;

import com.zking.gofcrm.authority.model.SysFunction;

public interface SysFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String funId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbg.generated
     */
    int insert(SysFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbg.generated
     */
    int insertSelective(SysFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbg.generated
     */
    SysFunction selectByPrimaryKey(String funId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysFunction record);
}