package com.zking.gofcrm.basd.model;

import org.springframework.stereotype.Component;

import java.io.Serializable;

/**
 *
 * 数据字典表  对应的 实体
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table crm_dict
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Component
public class Dictionary implements Serializable {
    /**
     * Database Column Remarks:
     *   字典编号，自增长
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_dict.dict_id
     *
     * @mbg.generated
     */
    private Integer dictId;

    /**
     * Database Column Remarks:
     *   字典类型（字段所属的表名）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_dict.dict_type
     *
     * @mbg.generated
     */
    private String dictType;

    /**
     * Database Column Remarks:
     *   字典条例
     *  用于生成下拉框的值
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_dict.dict_item
     *
     * @mbg.generated
     */
    private String dictItem;

    /**
     * Database Column Remarks:
     *   值所属数据的编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_dict.dict_value_id
     *
     * @mbg.generated
     */
    private String dictValueId;

    /**
     * Database Column Remarks:
     *   字典指向 具体的值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_dict.dict_value
     *
     * @mbg.generated
     */
    private String dictValue;

    /**
     * Database Column Remarks:
     *   是否可以编辑 1可编辑 2不可编辑
     * @mbg.generated
     */
    private Integer dictIsEditable;





    /**
     * @return the value of crm_dict.dict_id
     *
     * @mbg.generated
     */
    public Integer getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_dict.dict_id
     *
     * @param dictId the value for crm_dict.dict_id
     *
     * @mbg.generated
     */
    public void setDictId(Integer dictId) {
        this.dictId = dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_dict.dict_type
     *
     * @return the value of crm_dict.dict_type
     *
     * @mbg.generated
     */
    public String getDictType() {
        return dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_dict.dict_type
     *
     * @param dictType the value for crm_dict.dict_type
     *
     * @mbg.generated
     */
    public void setDictType(String dictType) {
        this.dictType = dictType == null ? null : dictType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_dict.dict_item
     *
     * @return the value of crm_dict.dict_item
     *
     * @mbg.generated
     */
    public String getDictItem() {
        return dictItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_dict.dict_item
     *
     * @param dictItem the value for crm_dict.dict_item
     *
     * @mbg.generated
     */
    public void setDictItem(String dictItem) {
        this.dictItem = dictItem == null ? null : dictItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_dict.dict_value_id
     *
     * @return the value of crm_dict.dict_value_id
     *
     * @mbg.generated
     */
    public String getDictValueId() {
        return dictValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_dict.dict_value_id
     *
     * @param dictValueId the value for crm_dict.dict_value_id
     *
     * @mbg.generated
     */
    public void setDictValueId(String dictValueId) {
        this.dictValueId = dictValueId == null ? null : dictValueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_dict.dict_value
     *
     * @return the value of crm_dict.dict_value
     *
     * @mbg.generated
     */
    public String getDictValue() {
        return dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_dict.dict_value
     *
     * @param dictValue the value for crm_dict.dict_value
     *
     * @mbg.generated
     */
    public void setDictValue(String dictValue) {
        this.dictValue = dictValue == null ? null : dictValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_dict.dict_is_editable
     *
     * @return the value of crm_dict.dict_is_editable
     *
     * @mbg.generated
     */
    public Integer getDictIsEditable() {
        return dictIsEditable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_dict.dict_is_editable
     *
     * @param dictIsEditable the value for crm_dict.dict_is_editable
     *
     * @mbg.generated
     */
    public void setDictIsEditable(Integer dictIsEditable) {
        this.dictIsEditable = dictIsEditable;
    }


    @Override
    public String toString() {
        return "Dictionary{" +
                "dictId=" + dictId +
                ", dictType='" + dictType + '\'' +
                ", dictItem='" + dictItem + '\'' +
                ", dictValueId='" + dictValueId + '\'' +
                ", dictValue='" + dictValue + '\'' +
                ", dictIsEditable=" + dictIsEditable +
                '}';
    }

}