package com.zking.gofcrm.basd.model;

import java.io.Serializable;

/**
 * 说明：这是库存实体（仓库）
 * User: jzw
 * Date: 2018-02-15
 * Time: 12:35
 */
public class SellStorage implements Serializable {
    /**
     * Database Column Remarks:
     *   库存编号，主键自动增长
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_storage.stk_id
     *
     * @mbg.generated
     */
    private Integer stkId;

    /**
     * 产品对象
     */
    private SellProduct sellProduct;

    /**
     * Database Column Remarks:
     *   仓库
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_storage.stk_warehouse
     *
     * @mbg.generated
     */
    private String stkWarehouse;

    /**
     * Database Column Remarks:
     *   货位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_storage.stk_ware
     *
     * @mbg.generated
     */
    private String stkWare;

    /**
     * Database Column Remarks:
     *   件数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_storage.stk_count
     *
     * @mbg.generated
     */
    private Integer stkCount;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sell_storage.stk_memo
     *
     * @mbg.generated
     */
    private String stkMemo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_storage.stk_id
     *
     * @return the value of sell_storage.stk_id
     *
     * @mbg.generated
     */
    public Integer getStkId() {
        return stkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_storage.stk_id
     *
     * @param stkId the value for sell_storage.stk_id
     *
     * @mbg.generated
     */
    public void setStkId(Integer stkId) {
        this.stkId = stkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_storage.stk_prod_id
     *
     * @return the value of sell_storage.stk_prod_id
     *
     * @mbg.generated
     */
    public String getStkProdId() {
        return this.sellProduct.getProdId();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_storage.stk_prod_id
     *
     * @param stkProdId the value for sell_storage.stk_prod_id
     *
     * @mbg.generated
     */
    public void setStkProdId(String stkProdId) {
        this.sellProduct.setProdId(stkProdId == null ? null : stkProdId.trim());
    }

    public SellProduct getSellProduct() {
        return sellProduct;
    }

    public void setSellProduct(SellProduct sellProduct) {
        this.sellProduct = sellProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_storage.stk_warehouse
     *
     * @return the value of sell_storage.stk_warehouse
     *
     * @mbg.generated
     */
    public String getStkWarehouse() {
        return stkWarehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_storage.stk_warehouse
     *
     * @param stkWarehouse the value for sell_storage.stk_warehouse
     *
     * @mbg.generated
     */
    public void setStkWarehouse(String stkWarehouse) {
        this.stkWarehouse = stkWarehouse == null ? null : stkWarehouse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_storage.stk_ware
     *
     * @return the value of sell_storage.stk_ware
     *
     * @mbg.generated
     */
    public String getStkWare() {
        return stkWare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_storage.stk_ware
     *
     * @param stkWare the value for sell_storage.stk_ware
     *
     * @mbg.generated
     */
    public void setStkWare(String stkWare) {
        this.stkWare = stkWare == null ? null : stkWare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_storage.stk_count
     *
     * @return the value of sell_storage.stk_count
     *
     * @mbg.generated
     */
    public Integer getStkCount() {
        return stkCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_storage.stk_count
     *
     * @param stkCount the value for sell_storage.stk_count
     *
     * @mbg.generated
     */
    public void setStkCount(Integer stkCount) {
        this.stkCount = stkCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sell_storage.stk_memo
     *
     * @return the value of sell_storage.stk_memo
     *
     * @mbg.generated
     */
    public String getStkMemo() {
        return stkMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sell_storage.stk_memo
     *
     * @param stkMemo the value for sell_storage.stk_memo
     *
     * @mbg.generated
     */
    public void setStkMemo(String stkMemo) {
        this.stkMemo = stkMemo == null ? null : stkMemo.trim();
    }
}